RotaSeguraWeb/Controllers/DriverController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RotaSeguraWeb.Models;
using static RotaSeguraWeb.Models.Enuns.Enum;

namespace RotaSeguraWeb.Controllers
{
    public class DriverController : Controller
    {
        // GET: DriverController
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            int pageSize = 10; // Número de itens por página

            // Substitua a lógica abaixo para buscar os dados do seu repositório ou banco de dados
            List<DriverDTO> fakeDrivers = GetFakeDrivers();

            var model = fakeDrivers.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.PageNumber = pageNumber;
            ViewBag.TotalPages = (int)Math.Ceiling(fakeDrivers.Count / (double)pageSize);

            return View(fakeDrivers);
        }
        public  List<DriverDTO> GetFakeDrivers()
        {
            return new List<DriverDTO>
    {
        new DriverDTO
        {
            DId = 1,
            DName = "João Silva",
            DMobile = "123-456-7890",
            DAddress = "Rua das Flores, 123",
            DAge = 35,
            DLicenseno = "A123456",
            DLicenseExpDate = new DateTime(2025, 12, 31),
            DTotalExp = 10,
            DDoj = new DateTime(2018, 06, 01),
            DRef = "REF001",
            IsActive = DriveIsActive.Ativo,
            DFile = "file1.jpg",
            DFile1 = "file2.jpg",
            DCreatedBy = "Usuário A",
            DCreatedDate = DateTime.Now,
            DModifiedDate = DateTime.Now
        },
        new DriverDTO
        {
            DId = 2,
            DName = "Maria Santos",
            DMobile = "098-765-4321",
            DAddress = "Avenida Brasil, 456",
            DAge = 28,
            DLicenseno = "B789012",
            DLicenseExpDate = new DateTime(2024, 05, 15),
            DTotalExp = 5,
            DDoj = new DateTime(2020, 03, 01),
            DRef = "REF002",
            IsActive = DriveIsActive.Ativo,
            DFile = "file3.jpg",
            DFile1 = "file4.jpg",
            DCreatedBy = "Usuário B",
            DCreatedDate = DateTime.Now,
            DModifiedDate = DateTime.Now
        },
        new DriverDTO
        {
            DId = 3,
            DName = "Pedro Costa",
            DMobile = "321-654-9870",
            DAddress = "Rua Nova, 789",
            DAge = 45,
            DLicenseno = "C345678",
            DLicenseExpDate = new DateTime(2023, 10, 30),
            DTotalExp = 20,
            DDoj = new DateTime(2015, 11, 01),
            DRef = "REF003",
            IsActive = DriveIsActive.Inativo,
            DFile = "file5.jpg",
            DFile1 = "file6.jpg",
            DCreatedBy = "Usuário C",
            DCreatedDate = DateTime.Now,
            DModifiedDate = DateTime.Now
        }
        ,
        new DriverDTO
        {
            DId = 4,
            DName = "Pedro2 Costa",
            DMobile = "321-654-9870",
            DAddress = "Rua Nova, 789",
            DAge = 45,
            DLicenseno = "C345678",
            DLicenseExpDate = new DateTime(2023, 10, 30),
            DTotalExp = 20,
            DDoj = new DateTime(2015, 11, 01),
            DRef = "REF003",
            IsActive = DriveIsActive.Inativo,
            DFile = "file5.jpg",
            DFile1 = "file6.jpg",
            DCreatedBy = "Usuário C",
            DCreatedDate = DateTime.Now,
            DModifiedDate = DateTime.Now
        }
    };
        }


        // GET: DriverController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DriverController/Create
        public ActionResult Create()
        {
            ViewBag.IsActive = new List<SelectListItem>
            { new SelectListItem { Value = "", Text = "" },
             new SelectListItem { Value = "0", Text = "Inativo" },
             new SelectListItem { Value = "0", Text = "Ativo" },
            };
            return View();
        }

        // POST: DriverController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DriverDTO collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private DriverDTO GetFakeDriversPorId(int id)
        {
            var vehicles = GetFakeDrivers();
            return vehicles.FirstOrDefault(v => v.DId == id);
        }
        // GET: DriverController/Edit/5
        public ActionResult Edit(int id)
        {
            var vehicle = GetFakeDriversPorId(id);
            return View(vehicle);
        }

        // POST: DriverController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DriverController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DriverController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RotaSeguraWeb/Views/Driver/Create.cshtml
@model RotaSeguraWeb.Models.DriverDTO

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="content-wrapper">
    <h2>@ViewData["Title"]</h2>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <!-- Primeira coluna -->
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="DName" class="control-label"></label>
                                    <input asp-for="DName" class="form-control" />
                                    <span asp-validation-for="DName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DMobile" class="control-label"></label>
                                    <input asp-for="DMobile" class="form-control" />
                                    <span asp-validation-for="DMobile" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DAddress" class="control-label"></label>
                                    <input asp-for="DAddress" class="form-control" />
                                    <span asp-validation-for="DAddress" class="text-danger"></span>
                                </div>
                            </div>
                            <!-- Segunda coluna -->
                            <div class="col-md-4">

                                <div class="form-group">
                                    <label asp-for="DAge" class="control-label"></label>
                                    <input asp-for="DAge" class="form-control" />
                                    <span asp-validation-for="DAge" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DLicenseno" class="control-label"></label>
                                    <input asp-for="DLicenseno" class="form-control" />
                                    <span asp-validation-for="DLicenseno" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                        <label asp-for="IsActive" class="control-label"></label>
                                        <select asp-for="IsActive" class="form-control" asp-items="@(ViewBag.IsActive)"></select>
                                        <span asp-validation-for="IsActive" class="text-danger"></span>
                                    </div>
                            </div>
                            <!-- Terceira coluna -->
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="DLicenseExpDate" class="control-label"></label>
                                    <input asp-for="DLicenseExpDate" class="form-control" />
                                    <span asp-validation-for="DLicenseExpDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DTotalExp" class="control-label"></label>
                                    <input asp-for="DTotalExp" class="form-control" />
                                    <span asp-validation-for="DTotalExp" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DDoj" class="control-label"></label>
                                    <input asp-for="DDoj" class="form-control" />
                                    <span asp-validation-for="DDoj" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DRef" class="control-label"></label>
                                    <input asp-for="DRef" class="form-control" />
                                    <span asp-validation-for="DRef" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Sallvar" class="btn btn-primary" />
                            </div>
                             -
                            <div>
                                <a asp-action="Index">Voltar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

RotaSeguraWeb/Views/Driver/Edit.cshtml
@model RotaSeguraWeb.Models.DriverDTO

@{
    ViewData["Title"] = "Edit";
}

<hr />
<section class="content-wrapper">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="DId" class="control-label"></label>
                                    <input asp-for="DId" class="form-control" />
                                    <span asp-validation-for="DId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DName" class="control-label"></label>
                                    <input asp-for="DName" class="form-control" />
                                    <span asp-validation-for="DName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DMobile" class="control-label"></label>
                                    <input asp-for="DMobile" class="form-control" />
                                    <span asp-validation-for="DMobile" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DAddress" class="control-label"></label>
                                    <input asp-for="DAddress" class="form-control" />
                                    <span asp-validation-for="DAddress" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DFile1" class="control-label"></label>
                                    <input asp-for="DFile1" class="form-control" />
                                    <span asp-validation-for="DFile1" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DCreatedDate" class="control-label"></label>
                                    <input asp-for="DCreatedDate" class="form-control" />
                                    <span asp-validation-for="DCreatedDate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="DModifiedDate" class="control-label"></label>
                                    <input asp-for="DModifiedDate" class="form-control" />
                                    <span asp-validation-for="DModifiedDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DAge" class="control-label"></label>
                                    <input asp-for="DAge" class="form-control" />
                                    <span asp-validation-for="DAge" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DLicenseno" class="control-label"></label>
                                    <input asp-for="DLicenseno" class="form-control" />
                                    <span asp-validation-for="DLicenseno" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DLicenseExpDate" class="control-label"></label>
                                    <input asp-for="DLicenseExpDate" class="form-control" />
                                    <span asp-validation-for="DLicenseExpDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DTotalExp" class="control-label"></label>
                                    <input asp-for="DTotalExp" class="form-control" />
                                    <span asp-validation-for="DTotalExp" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DCreatedBy" class="control-label"></label>
                                    <input asp-for="DCreatedBy" class="form-control" />
                                    <span asp-validation-for="DCreatedBy" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="DDoj" class="control-label"></label>
                                    <input asp-for="DDoj" class="form-control" />
                                    <span asp-validation-for="DDoj" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DRef" class="control-label"></label>
                                    <input asp-for="DRef" class="form-control" />
                                    <span asp-validation-for="DRef" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="IsActive" class="control-label"></label>
                                    <input asp-for="IsActive" class="form-control" />
                                    <span asp-validation-for="IsActive" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DFile" class="control-label"></label>
                                    <input asp-for="DFile" class="form-control" />
                                    <span asp-validation-for="DFile" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DCreatedDate" class="control-label"></label>
                                    <input asp-for="DCreatedDate" class="form-control" />
                                    <span asp-validation-for="DCreatedDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DModifiedDate" class="control-label"></label>
                                    <input asp-for="DModifiedDate" class="form-control" />
                                    <span asp-validation-for="DModifiedDate" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
</section>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

RotaSeguraWeb/Views/Driver/Index.cshtml
@using static RotaSeguraWeb.Models.Enuns.Enum
@model IEnumerable<RotaSeguraWeb.Models.DriverDTO>
@{
    int pageNumber = ViewBag.PageNumber;
    int totalPages = ViewBag.TotalPages;
}
@{
    ViewData["Title"] = "Index";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<div class="content-wrapper">
    <H2>
        <a asp-action="Create">Adicionar Novo</a>
    </H2>
    <section class="content">
        <div class="container-fluid">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.First().DId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().DName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().DMobile)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().DLicenseno)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().DLicenseExpDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().DCreatedDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().IsActive)
                        </th>
                        <th>AÇÕES</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DMobile)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DLicenseno)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DLicenseExpDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DCreatedDate)
                                </td>
                                <td>
                                    @Enum.GetName(typeof(DriveIsActive), item.IsActive)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Driver", new { id = item.DId  })" class="icon-action">
                                        <i class="fa fa-edit"></i>
                                    </a> |
                                    <a href="@Url.Action("Details", "Driver", new { id = item.DId})" class="icon-action">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item @(pageNumber == 1 ? "disabled" : "")">
                        <a class="page-link" asp-action="Index" asp-route-pageNumber="@(pageNumber - 1)">Anterior</a>
                    </li>
                    @for (int i = 1; i <= totalPages; i++)
                    {
                        <li class="page-item @(i == pageNumber ? "active" : "")">
                            <a class="page-link" asp-action="Index" asp-route-pageNumber="@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(pageNumber == totalPages ? "disabled" : "")">
                        <a class="page-link" asp-action="Index" asp-route-pageNumber="@(pageNumber + 1)">Próximo</a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</div>