RotaSeguraWeb/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RotaSeguraWeb.Models;
using static RotaSeguraWeb.Models.Enuns.Enum;

namespace RotaSeguraWeb.Controllers
{
    public class VehicleController : Controller
    {
        // GET: VehicleController
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            int pageSize = 10; // Número de itens por página

            // Substitua a lógica abaixo para buscar os dados do seu repositório ou banco de dados
            var vehicles = BuscarVeiculos();

            var model = vehicles.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.PageNumber = pageNumber;
            ViewBag.TotalPages = (int)Math.Ceiling(vehicles.Count / (double)pageSize);

            return View(model);
        }

        private static List<VehicleDTO> BuscarVeiculos()
        {
            // Create a list of vehicles with fake data
            return new List<VehicleDTO>
            {
                new VehicleDTO
                {
                    VId = 1,
                    VRegistrationNo = "ABC123",
                    VName = "Carro A",
                    VModel = "Modelo A",
                    VChassisNo = "CHASSISA",
                    VEngineNo = "ENGINEA",
                    VManufacturedBy = "Fabricante A",
                    VType = "Sedan",
                    VColor = "Azul",
                    VMileagePerLitre = "15",
                    VIsActive = VehicleIsActive.Ativo,
                    VGroup = 1,
                    VRegExpDate = "2024-01-01",
                    VApiUrl = "https://api.example.com",
                    VApiUsername = "userA",
                    VApiPassword = "passwordA",
                    VCreatedBy = "Usuario A",
                    VCreatedDate = DateTime.Now,
                    VModifiedDate = DateTime.Now
                },
                new VehicleDTO
                {
                    VId = 2,
                    VRegistrationNo = "XYZ789",
                    VName = "Carro B",
                    VModel = "Modelo B",
                    VChassisNo = "CHASSISB",
                    VEngineNo = "ENGINEB",
                    VManufacturedBy = "Fabricante B",
                    VType = "Hatchback",
                    VColor = "Vermelho",
                    VMileagePerLitre = "18",
                    VIsActive = VehicleIsActive.Inativo,
                    VGroup = 2,
                    VRegExpDate = "2025-02-01",
                    VApiUrl = "https://api.example2.com",
                    VApiUsername = "userB",
                    VApiPassword = "passwordB",
                    VCreatedBy = "Usuario B",
                    VCreatedDate = DateTime.Now,
                    VModifiedDate = DateTime.Now
                }
            };
        }
        private static VehicleDTO BuscarVeiculoPorId(int id)
        {
            var vehicles = BuscarVeiculos();
            return vehicles.FirstOrDefault(v => v.VId == id);
        }

        // GET: VehicleController/Details/5
        public ActionResult Details(int id)
        {
            var vehicle = BuscarVeiculoPorId(id);

            if (vehicle == null)
            {
                return NotFound(); // Ou RedirectToAction("Index") para redirecionar ao índice caso não encontre o veículo
            }

            return View(vehicle);
        }

        // GET: VehicleController/Create
        public ActionResult Create()
        {
            ViewBag.Types = new List<SelectListItem>
            {
                new SelectListItem { Value = "Car", Text = "Car" },
                new SelectListItem { Value = "Truck", Text = "Truck" },
                new SelectListItem { Value = "Motorcycle", Text = "Motorcycle" },
                // adicione aqui outras opções que desejar
            };

            ViewBag.Groups = new List<SelectListItem>
            {
                new SelectListItem { Value = "Group A", Text = "Group A" },
                new SelectListItem { Value = "Group B", Text = "Group B" },
                new SelectListItem { Value = "Group C", Text = "Group C" },
                // adicione aqui outras opções que desejar
            };

            return View();
        }

        // POST: VehicleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VehicleDTO collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VehicleController/Edit/5
        public ActionResult Edit(int id)
        {
            var vehicle = BuscarVeiculoPorId(id);
            ViewBag.Types = new List<SelectListItem>
            {
                new SelectListItem { Value = "Car", Text = "Car" },
                new SelectListItem { Value = "Truck", Text = "Truck" },
                new SelectListItem { Value = "Motorcycle", Text = "Motorcycle" },
                // adicione aqui outras opções que desejar
            };

            ViewBag.Groups = new List<SelectListItem>
            {
                new SelectListItem { Value = "Group A", Text = "Group A" },
                new SelectListItem { Value = "Group B", Text = "Group B" },
                new SelectListItem { Value = "Group C", Text = "Group C" },
                // adicione aqui outras opções que desejar
            };



            if (vehicle == null)
            {
                return NotFound(); // Ou RedirectToAction("Index") para redirecionar ao índice caso não encontre o veículo
            }

            return View(vehicle);
        }

        // POST: VehicleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VehicleController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VehicleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RotaSeguraWeb/Views/Vehicle/Create.cshtml
@model RotaSeguraWeb.Models.VehicleDTO

@{
    ViewData["Title"] = "Create";
}

<section class="content-wrapper">
    <h1>Detalhes do Veiculo</h1>
        <div class="container-fluid">
            <div class="container">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="VRegistrationNo" class="control-label"></label>
                                <input asp-for="VRegistrationNo" class="form-control" />
                                <span asp-validation-for="VRegistrationNo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VName" class="control-label"></label>
                                <input asp-for="VName" class="form-control" />
                                <span asp-validation-for="VName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VModel" class="control-label"></label>
                                <input asp-for="VModel" class="form-control" />
                                <span asp-validation-for="VModel" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="VChassisNo" class="control-label"></label>
                                <input asp-for="VChassisNo" class="form-control" />
                                <span asp-validation-for="VChassisNo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VEngineNo" class="control-label"></label>
                                <input asp-for="VEngineNo" class="form-control" />
                                <span asp-validation-for="VEngineNo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VManufacturedBy" class="control-label"></label>
                                <input asp-for="VManufacturedBy" class="form-control" />
                                <span asp-validation-for="VManufacturedBy" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="VType" class="control-label"></label>
                                <select asp-for="VType" class="form-control" asp-items="@(ViewBag.Types)"></select>
                                <span asp-validation-for="VType" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VColor" class="control-label"></label>
                                <input asp-for="VColor" class="form-control" />
                                <span asp-validation-for="VColor" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="VRegExpDate" class="control-label"></label>
                                <input asp-for="VRegExpDate" class="form-control" />
                                <span asp-validation-for="VRegExpDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VGroup" class="control-label"></label>
                                <select asp-for="VGroup" class="form-control" asp-items="@(ViewBag.Groups)"></select>
                                <span asp-validation-for="VGroup" class="text-danger"></span>
                            </div>
                        </div>
                       
                           
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="VApiUrl" class="control-label"></label>
                                <input asp-for="VApiUrl" class="form-control" />
                                <span asp-validation-for="VApiUrl" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VApiUsername" class="control-label"></label>
                                <input asp-for="VApiUsername" class="form-control" />
                                <span asp-validation-for="VApiUsername" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VApiPassword" class="control-label"></label>
                                <input asp-for="VApiPassword" class="form-control" />
                                <span asp-validation-for="VApiPassword" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

RotaSeguraWeb/Views/Vehicle/Details.cshtml
@using static RotaSeguraWeb.Models.Enuns.Enum
@model RotaSeguraWeb.Models.VehicleDTO

@{
    ViewData["Title"] = "Details";
}

<div class="content-wrapper">
    <h1>Detalhes do Veiculo</h1>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-body text-center">
                            <h5 class="card-title text-center">@Html.DisplayFor(model => model.VName)</h5>
                            <p class="card-text text-center">
                                Tipo: @Html.DisplayFor(model => model.VType)
                                <br />
                                Ativo: @Enum.GetName(typeof(VehicleIsActive), Model.VIsActive)
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="col-md-9">
                        <div class="card card-primary card-tabs">
                            <div class="card-header p-0 pt-1">
                                <ul class="nav nav-tabs" id="custom-tabs-two-tab" role="tablist">
                                    <li class="pt-2 px-3"><h3 class="card-title"></h3></li>
                                    <li class="nav-item  active">
                                        <a class="nav-link active" id="custom-tabs-two-home-tab" data-toggle="pill" href="#custom-tabs-two-home" role="tab" aria-controls="custom-tabs-two-home" aria-selected="false">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-two-profile-tab" data-toggle="pill" href="#custom-tabs-two-profile" role="tab" aria-controls="custom-tabs-two-profile" aria-selected="false">Reservas</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-two-messages-tab" data-toggle="pill" href="#custom-tabs-two-messages" role="tab" aria-controls="custom-tabs-two-messages" aria-selected="false">Cerca Geografica</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="custom-tabs-two-settings-tab" data-toggle="pill" href="#custom-tabs-two-settings" role="tab" aria-controls="custom-tabs-two-settings" aria-selected="true">Receita de Despesas</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content" id="custom-tabs-two-tabContent">
                                    <div class="tab-pane fade  active show" id="custom-tabs-two-home" role="tabpanel" aria-labelledby="custom-tabs-two-home-tab">
                                        <table class="table table-striped">
                                            <tbody>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VRegistrationNo)</th>
                                                    <td>@Html.DisplayFor(model => model.VRegistrationNo)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VName)</th>
                                                    <td>@Html.DisplayFor(model => model.VName)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VModel)</th>
                                                    <td>@Html.DisplayFor(model => model.VModel)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VChassisNo)</th>
                                                    <td>@Html.DisplayFor(model => model.VChassisNo)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VEngineNo)</th>
                                                    <td>@Html.DisplayFor(model => model.VEngineNo)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VManufacturedBy)</th>
                                                    <td>@Html.DisplayFor(model => model.VManufacturedBy)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VMileagePerLitre)</th>
                                                    <td>@Html.DisplayFor(model => model.VMileagePerLitre)</td>
                                                </tr>

                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VApiUrl)</th>
                                                    <td>@Html.DisplayFor(model => model.VApiUrl)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VApiUsername)</th>
                                                    <td>@Html.DisplayFor(model => model.VApiUsername)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VApiPassword)</th>
                                                    <td>@Html.DisplayFor(model => model.VApiPassword)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VCreatedDate)</th>
                                                    <td>@Html.DisplayFor(model => model.VCreatedDate)</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">@Html.DisplayNameFor(model => model.VModifiedDate)</th>
                                                    <td>@Html.DisplayFor(model => model.VModifiedDate)</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div>
                                            @Html.ActionLink("Editar", "Edit", new {id = Model.VId }, new {@class = "btn btn-block bg-gradient-success btn-lg"})
                                            <a asp-action="Index" class="btn btn-block bg-gradient-primary  btn-lg">Voltar</a>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="custom-tabs-two-profile" role="tabpanel" aria-labelledby="custom-tabs-two-profile-tab">
                                        2
                                    </div>
                                    <div class="tab-pane fade" id="custom-tabs-two-messages" role="tabpanel" aria-labelledby="custom-tabs-two-messages-tab">
                                        3
                                    </div>
                                    <div class="tab-pane fade" id="custom-tabs-two-settings" role="tabpanel" aria-labelledby="custom-tabs-two-settings-tab">
                                        4
                                    </div>
                                </div>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

RotaSeguraWeb/Views/Vehicle/Index.cshtml
@using static RotaSeguraWeb.Models.Enuns.Enum
@model IEnumerable<RotaSeguraWeb.Models.VehicleDTO>
@{
    int pageNumber = ViewBag.PageNumber;
    int totalPages = ViewBag.TotalPages;
}
@{
    ViewData["Title"] = "Index";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="content-wrapper">
    <h1>Gerenciamento de Veiculos</h1>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.First().VId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().VRegistrationNo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().VName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().VModel)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().VChassisNo)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.First().VIsActive)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().VGroup)
                        </th>

                        <th>AÇÕES</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.VId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.VRegistrationNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.VName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.VModel)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.VChassisNo)
                            </td>

                            <td>
                                @Enum.GetName(typeof(VehicleIsActive), item.VIsActive)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.VGroup)
                            </td>

                            <td>
                                <a href="@Url.Action("Edit", "Vehicle", new { id=item.VId  })" class="icon-action">
                                    <i class="fa fa-edit"></i>
                                </a> |
                                <a href="@Url.Action("Details", "Vehicle", new { id=item.VId})" class="icon-action">
                                    <i class="fa fa-eye"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
               
            </table>
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item @(pageNumber == 1 ? "disabled" : "")">
                        <a class="page-link" asp-action="Index" asp-route-pageNumber="@(pageNumber - 1)">Anterior</a>
                    </li>
                    @for (int i = 1; i <= totalPages; i++)
                    {
                        <li class="page-item @(i == pageNumber ? "active" : "")">
                            <a class="page-link" asp-action="Index" asp-route-pageNumber="@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(pageNumber == totalPages ? "disabled" : "")">
                        <a class="page-link" asp-action="Index" asp-route-pageNumber="@(pageNumber + 1)">Próximo</a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</div>